admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

app_speciality:
    resource: "@AdminBundle/Controller/SpecialityController.php"
    type:     annotation

Admin_Event:
    resource: "@AdminBundle/Controller/EventController.php"
    type:     annotation

app_pediatrician:
    resource: "@AdminBundle/Controller/PediatricianController.php"
    type:     annotation

app_Experience:
    resource: "@AdminBundle/Controller/SharedExperienceController.php"
    type:     annotation

app_CommentSharedExperience:
    resource: "@AdminBundle/Controller/CommentSharedExperienceController.php"
    type:     annotation

app_theme:
    resource: "@AdminBundle/Controller/ThemeController.php"
    type:     annotation