<?php

namespace AppBundle\Repository;

/**
 * BabySitterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BabySitterRepository extends \Doctrine\ORM\EntityRepository
{
}
