<?php

namespace AppBundle\Repository;

/**
 * CommentSharedExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentSharedExperienceRepository extends \Doctrine\ORM\EntityRepository
{
}
