<?php

namespace AppBundle\Repository;

/**
 * GovernorateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GovernorateRepository extends \Doctrine\ORM\EntityRepository
{
}
