<?php

namespace AppBundle\Repository;

/**
 * PediatricianRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PediatricianRepository extends \Doctrine\ORM\EntityRepository
{
}
