<?php

namespace AppBundle\Repository;

/**
 * PediatricianRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PediatricianRepository extends \Doctrine\ORM\EntityRepository
{

    public function containName($name) {
        $qb = $this->createQueryBuilder("e");
        $qb
            ->andWhere("e.name Like :name")
            ->setParameter('name', '%'.$name.'%' )
        ;
        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
