<?php

namespace AppBundle\Repository;

/**
 * SharedExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharedExperienceRepository extends \Doctrine\ORM\EntityRepository
{
}
