<?php
/**
 * Created by PhpStorm.
 * User: Ekram
 * Date: 2018-06-02
 * Time: 10:06
 */

namespace AppBundle\Repository;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ThemeRepository extends \Doctrine\ORM\EntityRepository
{

}

