<?php

namespace AppBundle\Repository;

/**
 * VaccineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VaccineRepository extends \Doctrine\ORM\EntityRepository
{


    function findVaccine($p)
    {
$query = $this->createQueryBuilder('p')
    ->select('p')
    ->where('p.date = :date')
    ->setParameter('date', $p)
    ->getQuery();

   return $query->getResult();
        
    }


}
