<?php

namespace AppBundle\Repository;

/**
 * VaccineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VaccineRepository extends \Doctrine\ORM\EntityRepository
{
}
