mobile:
    resource: "@mobileBundle/Resources/config/routing.yml"
    prefix:   /

Admin_comment_shared_experience:
    resource: "@AdminBundle/Controller/CommentSharedExperienceController.php"
    type:     annotation

Front_comment_shared_experience:
    resource: "@FrontBundle/Controller/CommentSharedExperienceController.php"
    type:     annotation

Admin_theme:
    resource: "@AdminBundle/Controller/ThemeController.php"
    type:     annotation

Front_theme:
    resource: "@FrontBundle/Controller/ThemeController.php"
    type:     annotation

Admin_shared_experience:
    resource: "@AdminBundle/Controller/SharedExperienceController.php"
    type:     annotation

Front_shared_experience:
    resource: "@FrontBundle/Controller/SharedExperienceController.php"
    type:     annotation

Front_event:
    resource: "@FrontBundle/Controller/EventController.php"
    type:     annotation

Admin_event:
    resource: "@AdminBundle/Controller/EventController.php"
    type:     annotation

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# routing userbundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

;obile:
    resource: "@mobileBundle/Resources/config/routing.yml"
    prefix: /mobile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:   /profile
discutea_forum:
    resource: "@DForumBundle/Resources/config/routing.yml"
    prefix:   /
esprit_api:
    resource: "@DForumBundle/Resources/config/routing.yml"
    prefix:   /
ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"

mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"